### ISSUE TITLE
Refactor required for compatibility with latest home assistant versions

### ISSUE THREAD

**Issue by frederik14** [kesteraernoudt/dobiss#122]
## Configuration

Home Assistant 2022.11.4
Supervisor 2022.12.1
Operating System 9.3
Frontend-versie: 20230110.0 - latest

## Describe the bug

The dobiss custom component doesn't work anymore in the latest version of home assistant since it requires the following refactor to be performed:
[refactor number entity](https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/)

In the latest version most of the entities are disabled with the following warning message:
![image](https://user-images.githubusercontent.com/13403049/212968015-32d28aad-c3aa-4e30-be47-a2f108827a33.png)

**Comment by kesteraernoudt** [comment]
This was already fixed in the latest release - if there are still issues, let me know, but others confirmed it to be working fine

**Comment by frederik14** [comment]
I still get the "device is disabled by Configuration-item" error message on the dobiss devices. The connection with the NXT server is established but the devices don't work. What can I do to trace the issue? (HA 2023.1.5)

**Comment by frederik14** [comment]
Hi, I found the issue. Dobiss was added multiple times as an integrations, with old configurations as disabled. Deleting the disabled dobiss integration fixed the issue.
