### ISSUE TITLE
Dimmer light is not working anymore with Home Assistant 2025

### ISSUE THREAD

**Issue by s0g4ut** [kesteraernoudt/dobiss#213]
## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by kesteraernoudt** [comment]
can you share your logs please? And which version are you running? The latest v1.10?

**Comment by samvanwelden** [comment]
Samen here, after 1.10 dimmers not working. Still on 2024.12.15
The rest works

**Comment by kesteraernoudt** [comment]
Can either of you test the dev version that I just pushed? Not sure how @Miolosh tested this?
I made a change for the dimmable lights, not sure if that's all that's needed. If you can share logs, that would be great

**Comment by Miolosh** [comment]
I could not test dimmers, since there are none in my home. Unsure if I can add one without actually having one so I could try and test. 
My first focus was to have to normal lights working.

**Comment by s0g4ut** [comment]
Not sure how to test a dev version. I’m quite new with GitHub. And yes I have the last 1.10 version for the Dobiss Hacs

**Comment by kesteraernoudt** [comment]
> I could not test dimmers, since there are none in my home. Unsure if I can add one without actually having one so I could try and test. Same for those colored lights My first focus was to have to normal lights working.

can you explain how to test a dev version? Maybe @s0g4ut can use this same method to test on his system?

**Comment by s0g4ut** [comment]
Enregistreur: homeassistant.components.light
Source: helpers/entity_platform.py:608
intégration: Lumière (documentation, problèmes)
S'est produit pour la première fois: 22:12:41 (6 occurrences)
Dernier enregistrement: 22:12:41

Error adding entity None for domain light with platform dobiss
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1096, in capability_attributes
    supported_features = self.supported_features
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dobiss/light.py", line 157, in supported_features
    supports = LightEntityFeature.BRIGHTNESS
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'LightEntityFeature' has no attribute 'BRIGHTNESS'

**Comment by kesteraernoudt** [comment]
thank you! I've pushed a new version to dev that should fix this issue. Can you test again?

**Comment by Miolosh** [comment]
I did not find a very easy way to do this yet. I am quite new to this. I used the file editor and since we only worked in the lights, I deleted the lights.py in the dobiss integration with the one in the dev branch.

**Comment by samvanwelden** [comment]
I replaced the ight.py with your newer one, but this does not fix the dim lights.

still on 2024.12.5

 File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 284, in async_update_group_state
    color_mode_count = Counter(itertools.chain(all_color_modes))
  File "/usr/local/lib/python3.13/collections/__init__.py", line 608, in __init__
    self.update(iterable, **kwds)

**Comment by s0g4ut** [comment]
J’ai fait de même et voici mon erreur 
Enregistreur: homeassistant.components.light
Source: helpers/entity_platform.py:608
intégration: Lumière (documentation, problèmes)
S'est produit pour la première fois: 22:43:04 (6 occurrences)
Dernier enregistrement: 22:43:04

Error adding entity None for domain light with platform dobiss
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1116, in capability_attributes
    if LightEntityFeature.EFFECT in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'in <string>' requires string as left operand, not LightEntityFeature

**Comment by kesteraernoudt** [comment]
ok thanks - uploaded new version. I think I was wrong with the features function. Hopefully this works

**Comment by samvanwelden** [comment]
@kesteraernoudt -> the new updated file worked for me! thanks!

**Comment by kesteraernoudt** [comment]
> @kesteraernoudt -> the new updated file worked for me! thanks!

which version of HA are you using? 2025 or 2024?

**Comment by samvanwelden** [comment]
2025, latest version

**Comment by kesteraernoudt** [comment]
> So all fine with;
> 
> Core 2025.1.0 Supervisor 2024.12.3 Operating System 14.1 Frontend 20250103.0
> 
> I don't know if its something with your HACS plugin, but with the latest update all the color state of all my lights / groups are broken...

Thanks for testing. Are you saying it all works fine now, or that the lights at least show up again, but color state is not working?

If the latter, can you share the log?

**Comment by kesteraernoudt** [comment]
reading through the docs, I think removing that supported_features function should be ok. Can you try the latest dev version?

**Comment by s0g4ut** [comment]
You are the best!!! With the new dev version all my lights are working non dimmer and dimmer!!! Thanks a lot!!!

**Comment by kesteraernoudt** [comment]
> You are the best!!! With the new dev version all my lights are working non dimmer and dimmer!!! Thanks a lot!!!

Thank you for testing! I'll create a new release so hopefully it works for all!

**Comment by kesteraernoudt** [comment]
v1.11 released! Hopefully this works for everyone!

**Comment by s0g4ut** [comment]
I will try it :-)

**Comment by s0g4ut** [comment]
Yes perfect on my side, I will close the issue because it is not an issue anymore on my side :-)

**Comment by samvanwelden** [comment]
Everything fine here on my side too.

v1.11 fixed both lights and dimmers not visible..on Core 2025.1.0
colorstate is working on groups; the problem was frontend cache, i removed the dobbis integration completely and reinstalled it with the same names

@kesteraernoudt thanks for all this support, even if you don't have a dobbis installation anymore ;-)

**Comment by timvdsm** [comment]
Also for me everything is working as expected: HA 2025.1 with v1.11 of the dobiss integration. 

@kesteraernoudt once again ... thanks for the support!
